version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  open-pull-requests-limit: 99
  versioning-strategy: lockfile-only
