inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - "bin/*"
