language: ruby

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without production

cache: bundler

env:
  global:
    - GITHUB_OAUTH_CLIENT_KEY=xxx
    - GITHUB_OAUTH_CLIENT_SECRET=xxx

script:
  - bin/rspec spec/models
