dist: bionic
language: ruby

env:
  global:
    - DISABLE_SPRING=1
    - BLOG_TITLE=Blg
    - GITHUB_OAUTH_CLIENT_KEY=xxx
    - GITHUB_OAUTH_CLIENT_SECRET=xxx
    - GITHUB_USER=github_user

services:
  - postgresql

addons:
  chrome: stable

bundler_args: --without production

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - gem update --system 3.1.2
  - gem install bundler:2.1.4
  - sudo apt-get install chromium-chromedriver
  - nvm use stable

before_script:
  - bin/setup

script:
  - gem -v
  - bundler -v
  - bin/rspec
