language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - yarn

bundler_args: --without production

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

env:
  global:
    - GITHUB_OAUTH_CLIENT_KEY=xxx
    - GITHUB_OAUTH_CLIENT_SECRET=xxx

script:
  - bin/rspec
