version: "3.7"

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
      - rails_tmp:/app/tmp
      - home:/root
    environment:
      - BUNDLE_PATH=/app/.bundle
      - BUNDLE_JOBS=4
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - BLOG_TITLE
      - GITHUB_OAUTH_CLIENT_KEY
      - GITHUB_OAUTH_CLIENT_SECRET
      - GITHUB_USER
      - TWITTER_ID
      - GITHUB_ID
    command: bin/dev
    tty: true
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data

volumes:
  bundle:
  node_modules:
  rails_tmp:
  pg_data:
  home:
